import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { Bookmark, FolderPlus, ShieldCheck, ArrowUpRight, Trash2, Sparkles, Store } from "lucide-react";
import ClienteSection from "@/components/cliente/ClienteSection";
import { buscarNegocios, resolverImagenNegocio } from "@/services/negocioApi";
import { actualizarEspacio, leerEspacio, suscribirEspacio } from "@/services/clienteEspacioLocal";


export default function MiRedPage() {
  const [espacio, setEspacio] = useState(leerEspacio);
  const [negocios, setNegocios] = useState(null);
  const [error, setError] = useState("");
  const [nombreCarpeta, setNombreCarpeta] = useState("");
  const [filtro, setFiltro] = useState("todos");
  useEffect(() => suscribirEspacio(() => setEspacio(leerEspacio())), []);
  useEffect(() => { buscarNegocios({}).then(setNegocios).catch(() => setError("No pudimos comprobar el estado actual de los negocios.")); }, []);
  const porSlug = new Map((negocios || []).map(n => [n.slug, n]));
  const visibles = espacio.guardados.filter(g => filtro === "todos" || (filtro === "sin-carpeta" ? !g.carpetaId : g.carpetaId === filtro));
  function crearCarpeta(e) { e.preventDefault(); const nombre = nombreCarpeta.trim(); if (!nombre || nombre.length > 40) return; actualizarEspacio(actual => ({ ...actual, carpetas: [...actual.carpetas, { id: crypto.randomUUID(), nombre }] })); setNombreCarpeta(""); }
  function asignar(slug, carpetaId) { actualizarEspacio(actual => ({ ...actual, guardados: actual.guardados.map(g => g.slug === slug ? { ...g, carpetaId: carpetaId || null } : g) })); }
  function quitar(slug) { actualizarEspacio(actual => ({ ...actual, guardados: actual.guardados.filter(g => g.slug !== slug) })); }
  function borrarCarpeta(id) { actualizarEspacio(actual => ({ ...actual, carpetas: actual.carpetas.filter(c => c.id !== id), guardados: actual.guardados.map(g => g.carpetaId === id ? { ...g, carpetaId: null } : g) })); if (filtro === id) setFiltro("todos"); }
  function marcarVisto(g, n) { actualizarEspacio(actual => ({ ...actual, guardados: actual.guardados.map(item => item.slug === g.slug ? { ...item, capas: n.capasVerificacion?.filter(c => c.cumplida).map(c => c.capa) || [] } : item) })); }
  return <ClienteSection icon={Bookmark} eyebrow="Tus conexiones" title="Mi red de confianza" description="Guarda negocios, ordénalos en carpetas y vuelve a sus perfiles cuando los necesites." action={{ to: "/buscar", label: "Explorar negocios" }}>
    <div className="client-extra-note"><ShieldCheck className="size-5" /><p>Las carpetas y alertas de esta sección se guardan en este navegador, separadas por cuenta. Los cambios de verificación se comprueban al abrir esta página.</p></div>
    <div className="client-extra-split"><section className="client-extra-panel"><div className="flex items-center gap-2"><FolderPlus className="size-5 text-trust" /><h2 className="font-display text-lg font-bold">Mis carpetas</h2></div><form onSubmit={crearCarpeta} className="mt-4 flex gap-2"><input value={nombreCarpeta} onChange={e => setNombreCarpeta(e.target.value)} maxLength={40} placeholder="Nueva carpeta" aria-label="Nombre de la nueva carpeta" className="client-extra-input min-w-0 flex-1" /><button className="client-extra-button" type="submit" disabled={!nombreCarpeta.trim()}>Crear</button></form><div className="mt-4 space-y-2"><button onClick={() => setFiltro("todos")} className={`client-folder ${filtro === "todos" ? "is-active" : ""}`}>Todos <span>{espacio.guardados.length}</span></button><button onClick={() => setFiltro("sin-carpeta")} className={`client-folder ${filtro === "sin-carpeta" ? "is-active" : ""}`}>Sin carpeta <span>{espacio.guardados.filter(g => !g.carpetaId).length}</span></button>{espacio.carpetas.map(c => <div key={c.id} className="flex items-center gap-1"><button onClick={() => setFiltro(c.id)} className={`client-folder flex-1 ${filtro === c.id ? "is-active" : ""}`}>{c.nombre} <span>{espacio.guardados.filter(g => g.carpetaId === c.id).length}</span></button><button type="button" onClick={() => borrarCarpeta(c.id)} aria-label={`Eliminar carpeta ${c.nombre}`} className="client-icon-button"><Trash2 className="size-4" /></button></div>)}</div></section>
    <section className="client-extra-panel"><div className="flex items-center justify-between gap-2"><h2 className="font-display text-lg font-bold">Negocios guardados</h2><span className="text-sm text-muted-foreground">{visibles.length}</span></div>{error && <p role="alert" className="mt-3 text-sm text-danger">{error}</p>}{visibles.length === 0 ? <div className="client-extra-empty"><Store className="size-9 text-trust" /><strong>Aún no hay negocios en esta carpeta</strong><p>Marca el icono de guardado en una tarjeta del catálogo para añadirlos.</p><Link to="/buscar" className="client-extra-button">Descubrir negocios</Link></div> : <div className="mt-4 grid gap-3">{visibles.map(g => { const n = porSlug.get(g.slug); const capas = n?.capasVerificacion?.filter(c => c.cumplida).map(c => c.capa) || []; const cambios = n && (capas.some(c => !g.capas?.includes(c))); return <article key={g.slug} className="client-saved-card"><div className="client-saved-art">{n?.logoUrl ? <img src={resolverImagenNegocio(n.logoUrl)} alt="" className="size-full object-cover" /> : <Store className="size-6" />}</div><div className="min-w-0 flex-1"><strong className="block truncate">{n?.nombreComercial || g.slug}</strong><p className="text-xs text-muted-foreground">{n ? `${n.categoria?.nombre || "Negocio"}` : negocios ? "No aparece en el catálogo publicado" : "Comprobando perfil…"}</p>{cambios && <span className="client-change-tag"><Sparkles className="size-3" /> Nueva verificación</span>}</div><div className="flex flex-wrap items-center gap-2"><select aria-label={`Carpeta de ${n?.nombreComercial || g.slug}`} value={g.carpetaId || ""} onChange={e => asignar(g.slug, e.target.value)} className="client-extra-select"><option value="">Sin carpeta</option>{espacio.carpetas.map(c => <option key={c.id} value={c.id}>{c.nombre}</option>)}</select>{n && <Link to={`/negocio/publico/${g.slug}`} className="client-icon-button" aria-label={`Abrir ${n.nombreComercial}`}><ArrowUpRight className="size-4" /></Link>}{cambios && <button onClick={() => marcarVisto(g,n)} className="client-extra-small">Visto</button>}<button onClick={() => quitar(g.slug)} className="client-icon-button" aria-label={`Quitar ${g.slug} de guardados`}><Trash2 className="size-4" /></button></div></article>; })}</div>}</section></div>
  </ClienteSection>;
}
