import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { ArrowUpRight, Flag, Search, ShieldCheck, Info, Store, CheckCircle2 } from "lucide-react";
import ClienteSection from "@/components/cliente/ClienteSection";
import { buscarNegocios, obtenerNegocioPublico } from "@/services/negocioApi";
import { misDenuncias } from "@/services/denunciaApi";
import { consultarCedulaPublica } from "@/services/clienteVerificacionApi";

const ESTADO = { abierta: "En revisión", revisada: "Revisado", archivada: "Archivado" };
const fecha = valor => new Intl.DateTimeFormat("es-EC", { dateStyle: "medium" }).format(new Date(valor));

export default function SeguridadClientePage() {
  const [consulta, setConsulta] = useState("");
  const [resultados, setResultados] = useState(null);
  const [buscando, setBuscando] = useState(false);
  const [errorBusqueda, setErrorBusqueda] = useState("");
  const [denuncias, setDenuncias] = useState(null);
  const [errorDenuncias, setErrorDenuncias] = useState("");
  const [cedula, setCedula] = useState("");
  const [resultadoCedula, setResultadoCedula] = useState(null);
  const [consultandoCedula, setConsultandoCedula] = useState(false);
  const [errorCedula, setErrorCedula] = useState("");
  useEffect(() => { misDenuncias().then(setDenuncias).catch(e => setErrorDenuncias(e.message)); }, []);
  async function verificar(e) { e.preventDefault(); const q = consulta.trim(); if (!q) return; setBuscando(true); setErrorBusqueda(""); try { let lista; if (q.includes("/negocio/publico/")) { const slug = q.split("/negocio/publico/")[1]?.split(/[?#/]/)[0]; lista = slug ? [await obtenerNegocioPublico(slug)] : []; } else { lista = await buscarNegocios({ texto: q }); } setResultados(lista); } catch { setResultados([]); setErrorBusqueda("No pudimos consultar el catálogo. Inténtalo nuevamente."); } finally { setBuscando(false); } }
  async function verificarCedula(e) { e.preventDefault(); if (!/^\d{10}$/.test(cedula)) { setErrorCedula("Ingresa una cédula de 10 dígitos."); return; } setConsultandoCedula(true); setErrorCedula(""); try { setResultadoCedula(await consultarCedulaPublica(cedula)); } catch (err) { setResultadoCedula(null); setErrorCedula(err.message); } finally { setConsultandoCedula(false); } }
  return <ClienteSection icon={ShieldCheck} eyebrow="Transparencia" title="Centro de seguridad" description="Comprueba la información visible de un negocio publicado y sigue el estado de tus reportes.">
    <div className="client-extra-note"><Info className="size-5" /><p>La consulta de cédula solo encuentra negocios publicados. Un resultado vacío no confirma que la persona no tenga cuenta. CheckBiz aún no almacena RUC de negocios.</p></div>
    <section className="client-extra-panel mb-5"><div className="flex items-center gap-2"><ShieldCheck className="size-5 text-verified" /><h2 className="font-display text-lg font-bold">Verificador expreso de cédula</h2></div><p className="mt-2 text-sm text-muted-foreground">Si conoces la cédula del emprendedor, comprueba si corresponde a un negocio publicado y mira sus capas visibles.</p><form onSubmit={verificarCedula} className="mt-4 flex flex-wrap gap-2"><input value={cedula} onChange={e => { setCedula(e.target.value.replace(/\D/g, "").slice(0,10)); setResultadoCedula(null); }} inputMode="numeric" maxLength={10} className="client-extra-input min-w-[180px] flex-1" placeholder="Cédula de 10 dígitos" aria-label="Cédula de 10 dígitos" /><button className="client-extra-button" disabled={consultandoCedula || cedula.length !== 10} type="submit">{consultandoCedula ? "Consultando…" : "Consultar"}</button></form>{errorCedula && <p role="alert" className="mt-3 text-sm text-danger">{errorCedula}</p>}{resultadoCedula && (resultadoCedula.negocio ? <div className="client-history-card mt-4"><strong>{resultadoCedula.negocio.nombreComercial}</strong><p className="mt-1 text-sm text-muted-foreground">Trust Score {resultadoCedula.negocio.trustScore}/100</p><div className="mt-3 flex flex-wrap gap-1">{resultadoCedula.negocio.capasVerificacion.filter(c => c.cumplida).map(c => <span key={c.capa} className="client-audit-badge"><CheckCircle2 className="size-3" />{c.capa}</span>)}</div><Link to={`/negocio/publico/${resultadoCedula.negocio.slug}`} className="client-extra-link">Ver perfil publicado <ArrowUpRight className="size-3" /></Link></div> : <p className="mt-4 text-sm text-muted-foreground">No hay un negocio publicado vinculado a esta cédula. No mostramos información de cuentas privadas.</p>)}</section>
    <div className="client-extra-split"><section className="client-extra-panel"><div className="flex items-center gap-2"><Search className="size-5 text-trust" /><h2 className="font-display text-lg font-bold">Comprobar un negocio</h2></div><p className="mt-2 text-sm text-muted-foreground">Escribe su nombre comercial o pega el enlace de su Mini Landing.</p><form onSubmit={verificar} className="mt-4 flex gap-2"><input value={consulta} onChange={e => setConsulta(e.target.value)} className="client-extra-input min-w-0 flex-1" placeholder="Nombre o enlace del negocio" aria-label="Nombre o enlace del negocio" /><button className="client-extra-button" disabled={buscando || !consulta.trim()} type="submit">{buscando ? "Buscando…" : "Verificar"}</button></form>{errorBusqueda && <p role="alert" className="mt-3 text-sm text-danger">{errorBusqueda}</p>}{resultados && (resultados.length ? <div className="mt-4 space-y-3">{resultados.slice(0,6).map(n => <article key={n.slug} className="client-history-card"><div className="flex items-center gap-2"><Store className="size-5 text-trust" /><strong>{n.nombreComercial}</strong></div><p className="mt-1 text-xs text-muted-foreground">{n.ciudad || "Ciudad no indicada"} · Trust Score {n.trustScore}/100</p><div className="mt-3 flex flex-wrap gap-1">{(n.capasVerificacion || []).filter(c => c.cumplida).map(c => <span key={c.capa} className="client-audit-badge"><CheckCircle2 className="size-3" />{c.capa}</span>)}</div><Link to={`/negocio/publico/${n.slug}`} className="client-extra-link">Abrir perfil <ArrowUpRight className="size-3" /></Link></article>)}</div> : !errorBusqueda && <div className="client-extra-empty"><Search className="size-7 text-trust" /><strong>No encontramos negocios publicados</strong><p>Revisa el nombre o explora el catálogo.</p></div>)}</section>
    <section className="client-extra-panel"><div className="flex items-center gap-2"><Flag className="size-5 text-action" /><h2 className="font-display text-lg font-bold">Mis reportes</h2></div><p className="mt-2 text-sm text-muted-foreground">Aquí puedes seguir los reportes que enviaste desde el perfil de un negocio.</p>{errorDenuncias && <p role="alert" className="mt-3 text-sm text-danger">{errorDenuncias}</p>}{!denuncias && !errorDenuncias && <p className="mt-4 text-sm text-muted-foreground">Cargando reportes…</p>}{denuncias && (denuncias.length ? <div className="mt-4 space-y-3">{denuncias.map(d => <article key={d.id} className="client-history-card"><div className="flex items-center justify-between gap-2"><strong>Reporte del {fecha(d.creadoEn)}</strong><span className="client-audit-badge">{ESTADO[d.estado] || d.estado}</span></div><p className="mt-2 text-sm text-muted-foreground">{d.motivo}</p><p className="mt-2 text-xs text-muted-foreground">Referencia: {d.id.slice(0,8)}</p></article>)}</div> : <div className="client-extra-empty"><Flag className="size-8 text-action" /><strong>Sin reportes enviados</strong><p>Si detectas un problema, usa “Reportar” en el perfil público del negocio.</p></div>)}</section></div>
  </ClienteSection>;
}
